name: Tests

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Install modules
          run: yarn
        - name: Run tests
          run: yarn test