name: Tests

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies using yarn
        run: yarn install --frozen-lockfile --no-progress --prefer-offline
      - name: Run tests
        run: yarn test
